title: Michael Fichman # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <i><b>Cities, Data, Arts, Music, Community </b></i>
  <br><br>
  I'm data-savvy city planner and educator working in a range of fields, including nighttime economies, arts and culture, smart cities, transportation, parks and open space, and more.
  <br><br>
  <i>Researcher & City Planning Consultant</i> <br>
  PennPraxis<br><br>
  <i>Lecturer</i> 
  Urban Spatial Analytics<br>
  University of Pennsylvania Weitzman School of Design<br><br>
  <i>Data Scientist</i> <br>
  Center for Safe Mobility
  <br><br>
  <br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
